application: healthy-life-93504
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /$
  static_files: client/main.html
  upload: client/.*
- url: /(.+\..+)$
  static_files: client/\1
  upload: client/.*
- url: /.+
  script: server.main.app

libraries:
- name: webapp2
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- bootstrap/.*$
- bower_components/.*$
